## MusicGalleryData : RefCounted
## 音乐画廊屏幕的静态音轨数据。
## 扩展 RefCounted 以支持预加载兼容性（模式来自 AboutText.gd）。
extends RefCounted

const ENTRIES: Array[Dictionary] = [
	{"id": "LANSHANProject","title": "LANSHANProject","file": "res://assets/music/LANSHANProject.ogg"},
	{"id": "FirstDay","title": "FirstDay","file": "res://assets/music/FirstDay.ogg"},
	{"id": "Daylight","title": "Daylight","file": "res://assets/music/Daylight.ogg"},
	{"id": "DayAfterDay","title": "Day After Day","file": "res://assets/music/DayAfterDay.ogg"},
	{"id": "DayAfterDay2","title": "Day After Day 2","file": "res://assets/music/DayAfterDay2.ogg"},
	{"id": "What","title": "What","file": "res://assets/music/What.ogg"},
	{"id": "Noon","title": "Noon","file": "res://assets/music/Noon.ogg"},
	{"id": "MySecret","title": "My Secret","file": "res://assets/music/MySecret.ogg"},
	{"id": "Memories","title": "Memories","file": "res://assets/music/Memories.ogg"},
	{"id": "Inside","title": "Inside","file": "res://assets/music/Inside.ogg"},
	{"id": "Warning","title": "Warning","file": "res://assets/music/Warning.ogg"},
	{"id": "Autumn","title": "Autumn","file": "res://assets/music/Autumn.ogg"},
	{"id": "Finale","title": "Finale","file": "res://assets/music/Finale.ogg"},
	{"id": "Jingzhi Rd","title": "Jingzhi Rd.","file": "res://assets/music/Jingzhi Rd.ogg"},
	{"id": "JingzhiRdLib","title": "Jingzhi Rd. (Library Ver.)", "file": "res://assets/music/Jingzhi Rd.(library version).ogg"},
	{"id": "Qili Rd","title": "Qili Rd.","file": "res://assets/music/Qili Rd.ogg"},
	{"id": "illustration","title": "Illustration","file": "res://assets/music/illustration.ogg"},
	{"id": "TheGate","title": "The Gate","file": "res://assets/music/The Gate.ogg"},
	{"id": "Rainbow","title": "Rainbow","file": "res://assets/music/Rainbow.ogg"},
	{"id": "TheGate2","title": "The Gate (Final Ver.)","file": "res://assets/music/The Gate 2.ogg"},
	{"id": "040","title": "040","file": "res://assets/music/040.ogg"},
	{"id": "RAIN","title": "RAIN","file": "res://assets/music/RAIN.ogg"},
	{"id": "LANSHANProjectDemo", "title": "LANSHANProject Demo", "file": "res://assets/music/LANSHANProjectDemo.ogg"},
	{"id": "MayFlower","title": "May Flower","file": "res://assets/music/MayFlower.ogg"},
	{"id": "MayFlowerEP","title": "May Flower EP","file": "res://assets/music/MayFlowerEP.ogg"},
	{"id": "MayFlowerLove","title": "May Flower (Love Ver.)","file": "res://assets/music/MayFlower_LoveVersion.ogg"},
	{"id": "MayFlowerSingle","title": "May Flower (Single Ver.)","file": "res://assets/music/MayFlower_SingleVersion.ogg"},
	{"id": "Thought","title":"Thought","file":"res://assets/music/Thought.ogg"},
	{"id": "MayFlowerNormal","title":"May Flower (Normal Ver.)","file":"res://assets/music/MayFlowerNormalVersion.ogg"},
	{"id": "FalseDawn","title":"False Dawn","file":"res://assets/music/FalseDawn.ogg"},
	{"id": "Eden","title":"Eden","file":"res://assets/music/Eden.ogg"},
	{"id": "Where","title":"Where","file":"res://assets/music/Where.ogg"},
	{"id": "EdenNormalVer","title":"Eden (Normal Ver.)","file":"res://assets/music/Eden_NormalVer.ogg"},
	{"id": "RainingSeason","title":"Raining Season","file":"res://assets/music/RainingSeason.ogg"},
	{"id": "Overnight","title":"Overnight","file":"res://assets/music/Overnight.ogg"},
	{"id": "Overnight2","title":"Overnight 2","file":"res://assets/music/Overnight_2_.ogg"},
	{"id": "HuolanMount","title":"Huolan Mount.","file":"res://assets/music/HuolanMount.ogg"},
	{"id": "Library","title":"Library","file":"res://assets/music/Library.ogg"},
]
